
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 14 18:15:40 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 10;
  public static final int LCBR = 26;
  public static final int LTE = 20;
  public static final int UMINUS = 49;
  public static final int CALL_PREC = 51;
  public static final int INTEGER = 46;
  public static final int SEMI = 38;
  public static final int CONTINUE = 9;
  public static final int INT = 29;
  public static final int MINUS = 19;
  public static final int STATIC = 39;
  public static final int LT = 21;
  public static final int LP = 2;
  public static final int COMMA = 8;
  public static final int CLASS = 7;
  public static final int RP = 3;
  public static final int PLUS = 34;
  public static final int MULTIPLY = 31;
  public static final int QUOTE = 45;
  public static final int IF = 30;
  public static final int ASSIGN = 4;
  public static final int THIS = 41;
  public static final int ID = 47;
  public static final int DOT = 11;
  public static final int BOOLEAN = 5;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int RCBR = 36;
  public static final int LAND = 28;
  public static final int LB = 27;
  public static final int EQUAL = 12;
  public static final int TRUE = 42;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int RB = 35;
  public static final int LOR = 22;
  public static final int NULL = 33;
  public static final int MOD = 18;
  public static final int BREAK = 6;
  public static final int VOID = 43;
  public static final int GTE = 17;
  public static final int LOCATION_PREC = 50;
  public static final int ELSE = 14;
  public static final int WHILE = 44;
  public static final int NEQUAL = 32;
  public static final int CLASS_ID = 48;
  public static final int EXTENDS = 13;
  public static final int STRING = 40;
  public static final int LNEG = 23;
  public static final int FALSE = 15;
  public static final int GT = 16;
  public static final int LENGTH = 25;
}

