/* The following code was generated by JFlex 1.4.3 on 1/16/12 12:37 AM */

package IC.Parser;
import IC.Parser.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 1/16/12 12:37 AM from the specification file
 * <tt>src/IC/Parser/IC.lex</tt>
 */
public @SuppressWarnings(value={"all"}) class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int LINE_COMMENT_STATE = 6;
  public static final int STRING_SLASH_STATE = 4;
  public static final int COMMENT_STAR_STATE = 10;
  public static final int COMMENT_STATE = 8;
  public static final int YYINITIAL = 0;
  public static final int STRING_STATE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\60\1\57\2\0\1\62\22\0\1\62\1\43\1\55\2\0"+
    "\1\47\1\35\1\0\1\6\1\7\1\50\1\51\1\23\1\46\1\30"+
    "\1\27\1\2\11\5\1\0\1\54\1\45\1\10\1\34\2\0\32\3"+
    "\1\36\1\56\1\52\1\0\1\1\1\0\1\15\1\11\1\21\1\32"+
    "\1\14\1\33\1\40\1\41\1\25\1\4\1\20\1\13\1\4\1\16"+
    "\1\12\2\4\1\17\1\22\1\24\1\26\1\61\1\42\1\31\2\4"+
    "\1\37\1\44\1\53\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\4\0\1\2\1\3\1\4\1\5\1\3"+
    "\1\6\1\7\1\10\7\5\1\11\2\5\1\12\1\13"+
    "\1\5\1\14\1\2\1\15\1\16\1\5\1\17\1\2"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\5\1\1\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\31\1\41\1\42\16\5\1\43"+
    "\1\44\1\45\1\5\1\46\1\47\1\5\1\50\1\51"+
    "\1\52\6\5\1\53\10\5\1\54\6\5\1\55\1\5"+
    "\1\56\5\5\1\57\1\60\2\5\1\61\1\5\1\62"+
    "\4\5\1\63\2\5\1\64\1\65\1\5\1\66\1\5"+
    "\1\67\1\5\1\70\1\71\1\72\1\73\1\5\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\377\0\377\0\u01fe\0\u0231\0\u0264"+
    "\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363\0\377\0\u0396\0\u03c9"+
    "\0\u03fc\0\377\0\u042f\0\u0462\0\u0495\0\377\0\377\0\u04c8"+
    "\0\u04fb\0\u052e\0\u0561\0\377\0\377\0\377\0\377\0\377"+
    "\0\377\0\377\0\377\0\377\0\u0594\0\u05c7\0\377\0\377"+
    "\0\377\0\377\0\377\0\377\0\377\0\u05fa\0\u062d\0\377"+
    "\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5"+
    "\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7\0\u0198\0\377"+
    "\0\377\0\u092a\0\377\0\377\0\u095d\0\377\0\377\0\377"+
    "\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0198\0\u0ac2"+
    "\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27\0\u0198"+
    "\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0198\0\u0d8c"+
    "\0\u0198\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0198\0\u0198"+
    "\0\u0ebe\0\u0ef1\0\u0198\0\u0f24\0\u0198\0\u0f57\0\u0f8a\0\u0fbd"+
    "\0\u0ff0\0\u0198\0\u1023\0\u1056\0\u0198\0\u0198\0\u1089\0\u0198"+
    "\0\u10bc\0\u0198\0\u10ef\0\u0198\0\u0198\0\u0198\0\u0198\0\u1122"+
    "\0\u0198";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\12\1\20\1\21\1\12\1\22\1\23\1\12"+
    "\1\24\1\25\1\26\1\27\1\30\1\12\1\31\1\32"+
    "\2\12\1\33\1\34\1\35\1\36\1\37\2\12\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\7\2\54\1\55\1\54\55\56"+
    "\1\57\1\60\1\61\1\62\2\56\16\63\1\64\5\63"+
    "\1\64\30\63\2\64\1\0\3\63\57\54\1\65\53\54"+
    "\1\66\12\54\65\0\1\10\2\0\1\67\56\0\5\11"+
    "\3\0\12\11\1\0\3\11\2\0\3\11\4\0\3\11"+
    "\16\0\1\11\2\0\5\12\3\0\12\12\1\0\3\12"+
    "\2\0\3\12\4\0\3\12\16\0\1\12\3\0\1\13"+
    "\2\0\1\13\65\0\1\70\53\0\5\12\3\0\1\12"+
    "\1\71\4\12\1\72\3\12\1\0\3\12\2\0\3\12"+
    "\4\0\3\12\16\0\1\12\2\0\5\12\3\0\3\12"+
    "\1\73\6\12\1\0\3\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\2\12\1\74\7\12"+
    "\1\0\3\12\2\0\1\75\2\12\4\0\3\12\16\0"+
    "\1\12\2\0\5\12\3\0\3\12\1\76\6\12\1\0"+
    "\2\12\1\77\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\3\12\1\100\6\12\1\0\3\12"+
    "\2\0\3\12\4\0\3\12\16\0\1\12\2\0\5\12"+
    "\3\0\1\12\1\101\1\102\7\12\1\0\3\12\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\12\12\1\0\1\103\2\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\6\12\1\104\3\12"+
    "\1\0\3\12\2\0\3\12\4\0\1\12\1\105\1\12"+
    "\16\0\1\12\2\0\5\12\3\0\5\12\1\106\4\12"+
    "\1\0\3\12\2\0\2\12\1\107\4\0\3\12\16\0"+
    "\1\12\30\0\1\110\20\0\1\111\13\0\5\12\3\0"+
    "\4\12\1\112\5\12\1\0\3\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\11\0\1\113\107\0\1\114\26\0"+
    "\5\12\3\0\12\12\1\0\3\12\2\0\3\12\4\0"+
    "\1\12\1\115\1\12\16\0\1\12\11\0\1\116\116\0"+
    "\1\117\26\0\1\120\53\0\5\12\3\0\1\12\1\121"+
    "\10\12\1\0\3\12\2\0\3\12\4\0\3\12\16\0"+
    "\1\12\1\0\55\56\4\0\2\56\27\0\1\65\40\0"+
    "\1\67\56\0\5\12\3\0\1\12\1\122\10\12\1\0"+
    "\3\12\2\0\3\12\4\0\3\12\16\0\1\12\2\0"+
    "\5\12\3\0\3\12\1\123\6\12\1\0\3\12\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\5\12\1\124\4\12\1\0\3\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\2\0\5\12\3\0\11\12\1\125"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\12\12\1\0\1\126\2\12\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\12\12\1\0\3\12\2\0\3\12\4\0\2\12\1\127"+
    "\16\0\1\12\2\0\5\12\3\0\2\12\1\130\7\12"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\12\12\1\0\1\131\2\12\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\5\12\1\132\4\12\1\0\3\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\2\0\5\12\3\0\4\12\1\133"+
    "\5\12\1\0\3\12\2\0\3\12\4\0\3\12\16\0"+
    "\1\12\2\0\5\12\3\0\4\12\1\134\1\12\1\135"+
    "\3\12\1\0\3\12\2\0\3\12\4\0\3\12\16\0"+
    "\1\12\2\0\5\12\3\0\12\12\1\0\2\12\1\136"+
    "\2\0\3\12\4\0\3\12\16\0\1\12\2\0\5\12"+
    "\3\0\12\12\1\0\1\12\1\137\1\12\2\0\3\12"+
    "\4\0\3\12\16\0\1\12\2\0\5\12\3\0\12\12"+
    "\1\0\1\140\2\12\2\0\3\12\4\0\3\12\16\0"+
    "\1\12\2\0\5\12\3\0\2\12\1\141\7\12\1\0"+
    "\3\12\2\0\3\12\4\0\3\12\16\0\1\12\2\0"+
    "\5\12\3\0\12\12\1\0\1\12\1\142\1\12\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\12\12\1\0\1\12\1\143\1\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\2\0\5\12\3\0\2\12\1\144"+
    "\7\12\1\0\3\12\2\0\3\12\4\0\3\12\16\0"+
    "\1\12\2\0\5\12\3\0\4\12\1\145\5\12\1\0"+
    "\3\12\2\0\3\12\4\0\3\12\16\0\1\12\2\0"+
    "\5\12\3\0\12\12\1\0\3\12\2\0\3\12\4\0"+
    "\1\146\2\12\16\0\1\12\2\0\5\12\3\0\3\12"+
    "\1\147\6\12\1\0\3\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\3\12\1\150\6\12"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\2\12\1\151\7\12\1\0\3\12"+
    "\2\0\3\12\4\0\3\12\16\0\1\12\2\0\5\12"+
    "\3\0\12\12\1\0\2\12\1\152\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\2\0\5\12\3\0\12\12\1\0"+
    "\1\153\2\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\11\12\1\154\1\0\3\12\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\12\12\1\0\1\155\2\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\12\12\1\0\1\12"+
    "\1\156\1\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\3\12\1\157\6\12\1\0\3\12"+
    "\2\0\3\12\4\0\3\12\16\0\1\12\2\0\5\12"+
    "\3\0\11\12\1\160\1\0\3\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\2\0\5\12\3\0\11\12\1\161"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\2\12\1\162\7\12\1\0\3\12"+
    "\2\0\3\12\4\0\3\12\16\0\1\12\2\0\5\12"+
    "\3\0\12\12\1\0\3\12\2\0\1\12\1\163\1\12"+
    "\4\0\3\12\16\0\1\12\2\0\5\12\3\0\3\12"+
    "\1\164\6\12\1\0\3\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\7\12\1\165\2\12"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\12\12\1\0\1\166\2\12\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\5\12\1\167\4\12\1\0\3\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\2\0\5\12\3\0\6\12\1\170"+
    "\3\12\1\0\3\12\2\0\3\12\4\0\3\12\16\0"+
    "\1\12\2\0\5\12\3\0\12\12\1\0\1\12\1\171"+
    "\1\12\2\0\3\12\4\0\3\12\16\0\1\12\2\0"+
    "\5\12\3\0\11\12\1\172\1\0\3\12\2\0\3\12"+
    "\4\0\3\12\16\0\1\12\2\0\5\12\3\0\12\12"+
    "\1\0\1\12\1\173\1\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\5\12\1\174\4\12"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\3\12\1\175\6\12\1\0\3\12"+
    "\2\0\3\12\4\0\3\12\16\0\1\12\2\0\5\12"+
    "\3\0\3\12\1\176\6\12\1\0\3\12\2\0\3\12"+
    "\4\0\3\12\16\0\1\12\2\0\5\12\3\0\4\12"+
    "\1\177\5\12\1\0\3\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\12\12\1\0\3\12"+
    "\2\0\3\12\4\0\1\12\1\200\1\12\16\0\1\12"+
    "\2\0\5\12\3\0\12\12\1\0\3\12\2\0\1\12"+
    "\1\201\1\12\4\0\3\12\16\0\1\12\2\0\5\12"+
    "\3\0\5\12\1\202\4\12\1\0\3\12\2\0\3\12"+
    "\4\0\3\12\16\0\1\12\2\0\5\12\3\0\5\12"+
    "\1\203\4\12\1\0\3\12\2\0\3\12\4\0\3\12"+
    "\16\0\1\12\2\0\5\12\3\0\10\12\1\204\1\12"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\12\12\1\0\3\12\2\0\3\12"+
    "\4\0\1\205\2\12\16\0\1\12\2\0\5\12\3\0"+
    "\5\12\1\206\4\12\1\0\3\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\2\0\5\12\3\0\11\12\1\207"+
    "\1\0\3\12\2\0\3\12\4\0\3\12\16\0\1\12"+
    "\2\0\5\12\3\0\12\12\1\0\2\12\1\210\2\0"+
    "\3\12\4\0\3\12\16\0\1\12\2\0\5\12\3\0"+
    "\3\12\1\211\6\12\1\0\3\12\2\0\3\12\4\0"+
    "\3\12\16\0\1\12\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4437];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\3\0\1\10\1\11\4\1\2\11\10\1"+
    "\1\11\3\1\1\11\3\1\2\11\4\1\11\11\2\1"+
    "\7\11\2\1\1\11\17\1\2\11\1\1\2\11\1\1"+
    "\3\11\71\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	protected String stringHolder = "";
	public int getLineNumber() { return yyline+1; }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 26: 
          { String strTemp = stringHolder + "\"";
						  		stringHolder = "";
						  		yybegin(YYINITIAL);
						  		return new ValuedToken(yyline, sym.QUOTE, strTemp);
          }
        case 61: break;
        case 58: 
          { return new Token(yyline, sym.BOOLEAN);
          }
        case 62: break;
        case 10: 
          { return new Token(yyline, sym.DIVIDE);
          }
        case 63: break;
        case 57: 
          { return new Token(yyline, sym.STRING);
          }
        case 64: break;
        case 1: 
          { stringHolder += yytext();
          }
        case 65: break;
        case 46: 
          { return new Token(yyline, sym.NULL);
          }
        case 66: break;
        case 28: 
          { throw new LexicalError(yyline, "Can't start a new line in the middle of a string.");
          }
        case 67: break;
        case 43: 
          { return new Token(yyline, sym.NEW);
          }
        case 68: break;
        case 7: 
          { return new Token(yyline, sym.RP);
          }
        case 69: break;
        case 14: 
          { return new Token(yyline, sym.LCBR);
          }
        case 70: break;
        case 4: 
          { return new ValuedToken(yyline, sym.CLASS_ID, yytext() );
          }
        case 71: break;
        case 12: 
          { return new Token(yyline, sym.GT);
          }
        case 72: break;
        case 16: 
          { return new Token(yyline, sym.LT);
          }
        case 73: break;
        case 38: 
          { return new Token(yyline, sym.GTE);
          }
        case 74: break;
        case 3: 
          { return new ValuedToken(yyline, sym.INTEGER, yytext());
          }
        case 75: break;
        case 54: 
          { return new Token(yyline, sym.LENGTH);
          }
        case 76: break;
        case 39: 
          { return new Token(yyline, sym.LAND);
          }
        case 77: break;
        case 22: 
          { return new Token(yyline, sym.RCBR);
          }
        case 78: break;
        case 11: 
          { return new Token(yyline, sym.DOT);
          }
        case 79: break;
        case 32: 
          { yybegin(YYINITIAL);
          }
        case 80: break;
        case 41: 
          { return new Token(yyline, sym.LOR);
          }
        case 81: break;
        case 13: 
          { return new Token(yyline, sym.LB);
          }
        case 82: break;
        case 50: 
          { return new Token(yyline, sym.BREAK);
          }
        case 83: break;
        case 53: 
          { return new Token(yyline, sym.WHILE);
          }
        case 84: break;
        case 34: 
          { return new Token(yyline, sym.EQUAL);
          }
        case 85: break;
        case 33: 
          { throw new LexicalError(yyline, "leading zeroes are not allowed '"+yytext() +"'");
          }
        case 86: break;
        case 29: 
          { throw new LexicalError(yyline, "Can't put a tab in the middle of a string.");
          }
        case 87: break;
        case 5: 
          { return new ValuedToken(yyline, sym.ID, yytext());
          }
        case 88: break;
        case 8: 
          { return new Token(yyline, sym.ASSIGN);
          }
        case 89: break;
        case 20: 
          { return new Token(yyline, sym.PLUS);
          }
        case 90: break;
        case 55: 
          { return new Token(yyline, sym.RETURN);
          }
        case 91: break;
        case 47: 
          { return new Token(yyline, sym.TRUE);
          }
        case 92: break;
        case 44: 
          { return new Token(yyline, sym.INT);
          }
        case 93: break;
        case 59: 
          { return new Token(yyline, sym.EXTENDS);
          }
        case 94: break;
        case 49: 
          { return new Token(yyline, sym.VOID);
          }
        case 95: break;
        case 17: 
          { return new Token(yyline, sym.MINUS);
          }
        case 96: break;
        case 45: 
          { return new Token(yyline, sym.ELSE);
          }
        case 97: break;
        case 35: 
          { return new Token(yyline, sym.IF);
          }
        case 98: break;
        case 36: 
          { yybegin(LINE_COMMENT_STATE);
          }
        case 99: break;
        case 56: 
          { return new Token(yyline, sym.STATIC);
          }
        case 100: break;
        case 15: 
          { return new Token(yyline, sym.LNEG);
          }
        case 101: break;
        case 18: 
          { return new Token(yyline, sym.MOD);
          }
        case 102: break;
        case 48: 
          { return new Token(yyline, sym.THIS);
          }
        case 103: break;
        case 9: 
          { return new Token(yyline, sym.COMMA);
          }
        case 104: break;
        case 6: 
          { return new Token(yyline, sym.LP);
          }
        case 105: break;
        case 19: 
          { return new Token(yyline, sym.MULTIPLY);
          }
        case 106: break;
        case 52: 
          { return new Token(yyline, sym.FALSE);
          }
        case 107: break;
        case 27: 
          { yybegin( STRING_SLASH_STATE ); 
							  stringHolder += "\\";
          }
        case 108: break;
        case 60: 
          { return new Token(yyline, sym.CONTINUE);
          }
        case 109: break;
        case 21: 
          { return new Token(yyline, sym.RB);
          }
        case 110: break;
        case 23: 
          { return new Token(yyline, sym.SEMI);
          }
        case 111: break;
        case 30: 
          { throw new LexicalError(yyline, "Support only \\t, \\n, \\\\, \\\"  escape sequences.");
          }
        case 112: break;
        case 51: 
          { return new Token(yyline, sym.CLASS);
          }
        case 113: break;
        case 40: 
          { return new Token(yyline, sym.NEQUAL);
          }
        case 114: break;
        case 37: 
          { yybegin(COMMENT_STATE);
          }
        case 115: break;
        case 31: 
          { stringHolder += yytext(); 
							  yybegin( STRING_STATE );
          }
        case 116: break;
        case 42: 
          { return new Token(yyline, sym.LTE);
          }
        case 117: break;
        case 24: 
          { yybegin(STRING_STATE); /* switch to string state */ 
							  stringHolder += "\"" ;
          }
        case 118: break;
        case 2: 
          { throw new LexicalError(yyline, "illegal character '"+yytext() +"'");
          }
        case 119: break;
        case 25: 
          { 
          }
        case 120: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	if(yystate() != YYINITIAL && yystate() != LINE_COMMENT_STATE)
	{
			if(yystate() == COMMENT_STATE){
				throw new LexicalError(yyline,"Reached End Of File without closing multi-line comment");
			}
			else if(yystate() == STRING_STATE){
				throw new LexicalError(yyline,"Reached End Of File without closing quoted string");
			}
			else{
	    		throw new LexicalError(yyline,"Unexpected end of file");
	    	}
	}
  	return new Token(yyline, sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
